### PR TITLE
Fix hash calculation for catalog item of link

### PR DESCRIPTION
**Pull request by shirosaki**
`fime.symLinkTarget()` of some *.lnk files returns empty string on
Windows 10.  For example, Window Switcher.lnk, Shows Desktop.lnk
and Sticky Notes.lnk.
Hash is 0 and items are not added to catalog properly since hash
is used for item equality check.
As a workaround we calculate hash using `fullPath` if the link
target is empty.

### CODE REVIEW

**Comment by OpenNingia** [comment]
Wouldn't this mean that multiple link to the same target would be added multiple times?

**Comment by shirosaki** [comment]
If there are multiple links that `fime.symLinkTarget()` is empty and have same target, those links are added.
But `fime.symLinkTarget()` is empty, we cannot know the target is same or not.
Is there another way to get link target?

**Comment by OpenNingia** [comment]
I would like to understand why `fime.symLinkTarget()` returns an empty string. It could be a bug on Qt side. If that's the case then this is a simple workaround and should be at least decorated by a comment.

**Comment by shirosaki** [comment]
I found this article.
https://blogs.msdn.microsoft.com/oldnewthing/20160902-00/?p=94235
Special shortcut that points to virtual object exist.
It seems we cannot get target of such shortcut by normal way.

Shortcut of Windows 10 universal apps would be such special shortcut.
https://www.thurrott.com/windows/windows-10/5328/windows-10-tip-create-shortcuts-for-universal-apps

It seems that it is not a bug on Qt side, but Windows specification.

**Comment by OpenNingia** [comment]
Yes, I found the same source and edited my previous commit ( see above ). My suggestion in this case is to hash the whole .lnk file.

**Comment by shirosaki** [comment]
Thanks for comment.
I changed my patch to hash the whole content.

I found another issue. Hash calculation executed repeatedly while search timing.
This would not be good for performance.
I changed executing hash calculation after loading catalog file.

**Comment by OpenNingia** [comment]
Nice find! Merging right away...

**Pull request merged**
