### PR TITLE
fix: avoid adding a trailing space to the last argument when launchItem

### PR DESCRIPTION
**Pull request by jalbersdorfer**

### CODE REVIEW

**Comment by jalbersdorfer** [comment]
Hi, I don't know why AppVeyor build failes - but I'm pretty sure it has nothing to do with my changes.
Please comment.

**Comment by OpenNingia** [comment]
You're correct, it doesn't event start the build. They probably changed something in their image and the CI script stopped working.

**Comment by OpenNingia** [comment]
Appveyor should work now, can you try rebasing from master ?

**Comment by jalbersdorfer** [comment]
Now the build succeeds - I downloaded the artifact, tested my change and can confirm its functionality.

**Pull request merged**
